### PR TITLE
Reorganization of files

### PR DESCRIPTION
**Pull request by trelau**
- Put sources files into `src` and public API header into `include`
- Add patch for fixing geogram Windows link error
- Build static library for linking to TetWild.exe
- CMake adjustments

### CODE REVIEW

**Comment by jdumas** [comment]
Just a quick comment, but I would suggest putting the source files in a folder `src/TetWild` or `src/tetwild`, so that when you include them from another project there is no ambiguity (`#include <TetWild/Foo.h>`.

**Comment by trelau** [comment]
Added appveyor and travis builds in last commit. eventually we will add tests to the build services. i'll rebase on your last master commit and resolve any conflicts.

**Comment by trelau** [comment]
rebased on master complete

**Comment by trelau** [comment]
Building on OSX now in Travis-CI

**Pull request merged**
